# Section 1:  NumPy Solutions

### Import the library with alias np

In [2]:
import numpy as np

####  1. Create an array of  8 eights

In [4]:
np.ones(8)*8

array([8., 8., 8., 8., 8., 8., 8., 8.])

#### 2. Create an array of the integers from 10 to 50

In [5]:


np.arange(10,51)



array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### 3. Create a 3x3 matrix with values ranging from 22 to 30

In [6]:
np.arange(22,31).reshape(3,3)

array([[22, 23, 24],
       [25, 26, 27],
       [28, 29, 30]])

## Indexing
Use below Array 'arr' for Questions below. 

arr = np.arange(26,51).reshape(5,5)



In [8]:
arr = np.arange(26,51).reshape(5,5)
arr

array([[26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

#### 4. Use indexing on arr to get below output

       [[37, 38, 39, 40],
       [42, 43, 44, 45],
       [47, 48, 49, 50]]

In [9]:


arr[2:,1:]



array([[37, 38, 39, 40],
       [42, 43, 44, 45],
       [47, 48, 49, 50]])

#### 5. Use indexing on arr to get below output
Output should be 50

In [11]:


arr[4:,4][0]



50

#### 6. Use indexing on arr to get below output
      [[27],
       [32],
       [37]]

In [13]:


arr[0:3,1:2]


array([[27],
       [32],
       [37]])

#### 7. Use indexing on arr to get below output
      [46, 47, 48, 49, 50]

In [14]:


arr[-1]



array([46, 47, 48, 49, 50])

#### 8. Use indexing on arr to get below output
     [[41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]]

In [15]:


arr[3:]



array([[41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

### NumPy  Stats Functions

Use below given array 'arr'

In [16]:


arr = np.arange(10,40).reshape(6,5)
arr



array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

#### 9. Find the sum of all the values in given array 'arr'

In [17]:


np.sum(arr)



735

#### 10. Find the standard deviation of the values in given array 'arr'

In [18]:


np.std(arr)



8.65544144839919

#### 11.  Find the mean of all the values in given array 'arr'

In [19]:


np.mean(arr)



24.5

# Section 2: Pandas Solutions

#### Import pandas library  with alias pd

In [20]:
import pandas as pd

#### Read the given csv file

In [22]:
df=pd.read_csv('/Users/praburam.krishnamurthy/Downloads/sales.csv')
df

Observation  Dist_Taxi  Dist_Market  Dist_Metro  Store_Area  \
0              1     9796.0       5250.0     10703.0      1659.0   
1              2     8294.0       8186.0     12694.0      1461.0   
2              3    11001.0      14399.0     16991.0      1340.0   
3              4     8301.0      11188.0     12289.0      1451.0   
4              5    10510.0      12629.0     13921.0      1770.0   
..           ...        ...          ...         ...         ...   
927          928    12176.0       8518.0     15673.0      1582.0   
928          929     7214.0       8717.0     10553.0      1387.0   
929          930     7423.0      11708.0     13220.0      1200.0   
930          931    15082.0      14700.0     19617.0      1299.0   
931          932     9297.0      12537.0     14418.0      1174.0   

     Items_Available       Parking Coupon_Category  Daily_Customer_Count  \
0             1961.0          Open           CAT B                   530   
1             1752.0  Not Provided           CAT B                   210   
2             1609.0  Not Provided           CAT A                   720   
3             1748.0       Covered           CAT B                   620   
4             2111.0  Not Provided           CAT B                   450   
..               ...           ...             ...                   ...   
927           1910.0       Covered           CAT C                  1080   
928           1663.0          Open           CAT A                   850   
929           1436.0          Open           CAT A                  1060   
930           1560.0          Open           CAT B                   770   
931           1429.0       Covered           CAT C                  1110   

     Store_Sales  
0          66490  
1          39820  
2          54010  
3          53730  
4          46620  
..           ...  
927        66390  
928        82080  
929        76440  
930        96610  
931        54340  

[932 rows x 10 columns]

### 1. What are the unique values in  the column "Parking"?

In [23]:
df['Parking'].unique()

array(['Open', 'Not Provided', 'Covered', 'No Parking'], dtype=object)

### 2. What is the mean store area of the given data? 

In [25]:


df["Store_Area"].mean()



1511.862554112554

### 3.What are the different columns available in the dataset?

In [27]:
df.columns

Index(['Observation', 'Dist_Taxi', 'Dist_Market', 'Dist_Metro', 'Store_Area',
       'Items_Available', 'Parking', 'Coupon_Category', 'Daily_Customer_Count',
       'Store_Sales'],
      dtype='object')

### 4. Create a new series (series1) with only the values of third row

In [28]:


series1=df.iloc[2]
series1



Observation                        3
Dist_Taxi                    11001.0
Dist_Market                  14399.0
Dist_Metro                   16991.0
Store_Area                    1340.0
Items_Available               1609.0
Parking                 Not Provided
Coupon_Category                CAT A
Daily_Customer_Count             720
Store_Sales                    54010
Name: 2, dtype: object

### 5. Create a new dataframe(df_short which contain first 5 rows and two columns("Coupon_Category" and "Store_Sales")

In [29]:


df_short=df.loc[[0,1,2,3,4],["Coupon_Category","Store_Sales"]]
df_short



Coupon_Category  Store_Sales
0           CAT B        66490
1           CAT B        39820
2           CAT A        54010
3           CAT B        53730
4           CAT B        46620

In [30]:


df.head(5)[["Coupon_Category","Store_Sales"]]



Coupon_Category  Store_Sales
0           CAT B        66490
1           CAT B        39820
2           CAT A        54010
3           CAT B        53730
4           CAT B        46620

### 6. In dataframe df_short, replace the index with ["First Row","Second Row","Third Row", "Forth Row", "Fifth Row"]

In [31]:


df_short["Names"]=["First Row","Second Row","Third Row", "Forth Row", "Fifth Row"]
print(df_short)

df_short.set_index("Names",inplace=True)
df_short



  Coupon_Category  Store_Sales       Names
0           CAT B        66490   First Row
1           CAT B        39820  Second Row
2           CAT A        54010   Third Row
3           CAT B        53730   Forth Row
4           CAT B        46620   Fifth Row


Coupon_Category  Store_Sales
Names                                  
First Row            CAT B        66490
Second Row           CAT B        39820
Third Row            CAT A        54010
Forth Row            CAT B        53730
Fifth Row            CAT B        46620

### 7. Create a dataframe df2 fulfilling the given conditions - Dist_Metro>18000 and Parking= Open

In [32]:


df2=df[(df["Dist_Metro"]>18000) & (df["Parking"]=="Open")]
df2



Observation  Dist_Taxi  Dist_Market  Dist_Metro  Store_Area  \
88            89    14306.0      12591.0     18029.0      1441.0   
218          219    11195.0      16650.0     18762.0      1406.0   
338          339     9308.0      18281.0     18532.0      1771.0   
742          743    12973.0      15178.0     18836.0      1542.0   
791          792    14470.0      14517.0     18178.0      1645.0   
930          931    15082.0      14700.0     19617.0      1299.0   

     Items_Available Parking Coupon_Category  Daily_Customer_Count  \
88            1723.0    Open           CAT B                   330   
218           1677.0    Open           CAT A                   480   
338           2147.0    Open           CAT C                   430   
742           1844.0    Open           CAT B                   680   
791           1963.0    Open           CAT C                   900   
930           1560.0    Open           CAT B                   770   

     Store_Sales  
88         57860  
218        61660  
338        62710  
742        51380  
791        47300  
930        96610

### 8.What is the minimum store sales and the standard Deviation of store sales.

In [33]:
a=df["Store_Sales"].min()
b=df["Store_Sales"].std()
print("The Minimum of Store Sales is",a,"and the standard deviation of Store sales is", b )

The Minimum of Store Sales is 300 and the standard deviation of Store sales is 50253.63902204523


### 9. Group the dataset with respect to the variable 'Coupon_Category' using aggregation function mean()

In [35]:


df.groupby("Coupon_Category").mean()



TypeError: agg function failed [how->mean,dtype->object]

### 10. Drop the variable 'Parking' from the data.

In [39]:


df_1 = df.drop('Parking',axis=1)  
df_1.head()



KeyError: "['Parking'] not found in axis"

### 11. Export the Q10 dataframe without the 'Parking' column into a csv file.

In [40]:


df_1.to_csv('df.csv',index=False) 



AttributeError: 'NoneType' object has no attribute 'to_csv'

# Question on some additional functions

###  Display the first 10 entries of the dataset.  (Hint-use function head())

In [41]:


df.head(10)



Observation  Dist_Taxi  Dist_Market  Dist_Metro  Store_Area  \
0            1     9796.0       5250.0     10703.0      1659.0   
1            2     8294.0       8186.0     12694.0      1461.0   
2            3    11001.0      14399.0     16991.0      1340.0   
3            4     8301.0      11188.0     12289.0      1451.0   
4            5    10510.0      12629.0     13921.0      1770.0   
5            6     6665.0       5142.0      9972.0      1442.0   
6            7    13153.0      11869.0     17811.0      1542.0   
7            8     5882.0       9948.0     13315.0      1261.0   
8            9     7495.0      11589.0     13370.0      1090.0   
9           10     8233.0       7067.0     11400.0      1030.0   

   Items_Available Coupon_Category  Daily_Customer_Count  Store_Sales  
0           1961.0           CAT B                   530        66490  
1           1752.0           CAT B                   210        39820  
2           1609.0           CAT A                   720        54010  
3           1748.0           CAT B                   620        53730  
4           2111.0           CAT B                   450        46620  
5           1733.0           CAT B                   760        45260  
6           1858.0           CAT A                  1030        72240  
7           1507.0           CAT C                  1020        37720  
8           1321.0           CAT B                   680        46310  
9           1235.0           CAT C                  1130        44150

###  Display the last 5 entries of the dataset.(Hint- use function tail())

In [42]:
df.tail()

Observation  Dist_Taxi  Dist_Market  Dist_Metro  Store_Area  \
927          928    12176.0       8518.0     15673.0      1582.0   
928          929     7214.0       8717.0     10553.0      1387.0   
929          930     7423.0      11708.0     13220.0      1200.0   
930          931    15082.0      14700.0     19617.0      1299.0   
931          932     9297.0      12537.0     14418.0      1174.0   

     Items_Available Coupon_Category  Daily_Customer_Count  Store_Sales  
927           1910.0           CAT C                  1080        66390  
928           1663.0           CAT A                   850        82080  
929           1436.0           CAT A                  1060        76440  
930           1560.0           CAT B                   770        96610  
931           1429.0           CAT C                  1110        54340

### How many rows and columns are present in the dataset? (Hint- Use function shape)

In [44]:
df.shape

(932, 9)

###  What are the different data types of the variables in the given dataset? (Hint- Use function info())

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 932 entries, 0 to 931
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Observation           932 non-null    int64  
 1   Dist_Taxi             919 non-null    float64
 2   Dist_Market           919 non-null    float64
 3   Dist_Metro            931 non-null    float64
 4   Store_Area            924 non-null    float64
 5   Items_Available       917 non-null    float64
 6   Coupon_Category       932 non-null    object 
 7   Daily_Customer_Count  932 non-null    int64  
 8   Store_Sales           932 non-null    int64  
dtypes: float64(5), int64(3), object(1)
memory usage: 65.7+ KB


**Or you can use below command as well**

In [47]:
df.dtypes

Observation               int64
Dist_Taxi               float64
Dist_Market             float64
Dist_Metro              float64
Store_Area              float64
Items_Available         float64
Coupon_Category          object
Daily_Customer_Count      int64
Store_Sales               int64
dtype: object

# END