In [1]:
print("prabu")

prabu


In [1]:
2+2

4

In [2]:
3+3

6

In [1]:
def complicated_function(x,y):
    

SyntaxError: incomplete input (1602528718.py, line 2)

In [4]:
another_lambda=lambda x,y : x*x*x - y*y
print(another_lambda(2,3))

-1


In [20]:
class my_data_type:
    def first_function(self,val2):
        self.first_var = 1.7
        self.second_var = val2
    def second_function(self):
        return self.first_var*self.second_var

a=my_data_type()
a.first_function(2.2)
print(a.first_var)
print(a.second_function())

1.7
3.74


In [22]:
a.third_var=34
print(a.third_var)

34


In [24]:
class pet:
    def __init__(self,animal):
        self.animal=animal

In [29]:
my_dict = {var1 : 12, 'var2' : 23}
print(my_dict)

NameError: name 'var1' is not defined

In [32]:
for i in range(6):
    print(i)

0
1
2
3
4
5


In [34]:
array=[1,2,3]
for j in array:
    print(j)

1
2
3


In [41]:
if 4==4:
    print('true')
else:
    print('false')

true


In [53]:
import os
print(os.listdir('.'))

['.ipynb_checkpoints', 'Test.ipynb']


In [54]:
os.mkdir('test')

In [55]:
os.rename('test','testnew')

In [56]:
os.touch('file.txt')

AttributeError: module 'os' has no attribute 'touch'

In [64]:
file=open('\testnew\new.txt','w')
file.write('hello\n')
file.write('hello\n')
file.close()

In [68]:
import numpy as np
n1=np.array([[1,2,3],[4,5,6],[7,8,9]])

n1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
import numpy as np
n1=np.array([1,2,3,4,5,6])

type(n1)

numpy.ndarray

In [7]:
n2=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [8]:
n2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
n1=np.zeros([2,3])
n1

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
import numpy as np
n1=np.zeros([1,1])

n1

array([[0.]])

In [16]:
n3=np.full((2,3),(5))

n3

array([[5, 5, 5],
       [5, 5, 5]])

In [18]:
n4=np.arange(10,51,5)
n4

array([10, 15, 20, 25, 30, 35, 40, 45, 50])

In [19]:
n5=np.arange(50,100)
n5

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [22]:
n6=np.arange(1,102,10)
n6

array([  1,  11,  21,  31,  41,  51,  61,  71,  81,  91, 101])

In [32]:
n7=np.random.randint(10,1000,5)
n7

array([959, 681, 715,  73, 487])

In [34]:
n2=np.array([[1,2,3],[4,5,6],[7,8,9]])
n2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
n2.shape

(3, 3)

In [40]:
n2.shape=(4,3)


AttributeError: 'tuple' object has no attribute 'shape'

In [38]:
n2

(4, 3)

In [44]:
import numpy as np
n1=np.array([1,2,3,4])
n2=np.array([5,6,7,8])

np.column_stack((n1,n2))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [46]:
import numpy as np
n1=np.array([1,2,3,4,5,6])
n2=np.array([5,6,7,8])

np.intersect1d(n1,n2)

array([5, 6])

In [47]:
import numpy as np
n1=np.array([1,2,3,4,5,6])
n2=np.array([5,6,7,8])

np.setdiff1d(n1,n2)

array([1, 2, 3, 4])

In [48]:
import numpy as np
n1=np.array([1,2,3,4,5,6])
n2=np.array([5,6,7,8])

np.setdiff1d(n2,n1)

array([7, 8])

In [55]:
import numpy as np
n1=np.array([10,20])
n2=np.array([30,40])

np.sum([n1,n2])

100

In [56]:
import numpy as np
n1=np.array([10,20])
n2=np.array([30,40])

np.sum([n1,n2],axis=0)

array([40, 60])

In [57]:
import numpy as np
n1=np.array([10,20])
n2=np.array([30,40])

np.sum([n1,n2],axis=1)

array([30, 70])

In [59]:
import numpy as np
n1=np.array([10,20])
n2=np.array([30,40])

np.sum([n1,n2],axis=1)

array([30, 70])

In [61]:
import numpy as np
n1=np.array([10,20])
n1+=1


n1

array([11, 21])

In [62]:
import numpy as np
n1=np.array([10,20])
n1-=1


n1

array([ 9, 19])

In [69]:
import numpy as np
n1=np.array([10,20])
n1=n1*2


n1

array([20, 40])

In [67]:
import numpy as np
n1=np.array([10,20])
n1=n1/2


n1

array([ 5., 10.])

In [74]:
import numpy as np
n1=np.array([1,2,3,4])

np.mean(n1)

2.5

In [75]:
import numpy as np
n1=np.array([23,2,3,44])

np.median(n1)

13.0

In [76]:
import numpy as np
n1=np.array([23,2,3,44])

np.std(n1)

17.190113437671084

In [78]:
import numpy as np
n1=np.array([23,2,3,44])

np.std(n1)
np.save('test_numpy',n1)

In [81]:
n2=np.load('test_numpy.npy')
n2

array([23,  2,  3, 44])

In [84]:
import pandas as pd
n1=pd.Series([1,2,3])
n1

0    1
1    2
2    3
dtype: int64

In [86]:
type(n1)

pandas.core.series.Series

In [88]:
import pandas as pd
n1=pd.Series([1,2,3],index=['a','b','c'])
n1

a    1
b    2
c    3
dtype: int64

In [90]:
import pandas as pd
n1=pd.Series({'a':1,'b':2,'c':3})
n1

a    1
b    2
c    3
dtype: int64

In [94]:
import pandas as pd
n1=pd.Series({'d':1,'e':2,'c':3},index=['d','e','f'])
n1

d    1.0
e    2.0
f    NaN
dtype: float64

In [96]:
import pandas as pd
n1=pd.Series([1,2,3])
n1[2]

3

In [101]:
import pandas as pd
n1=pd.Series([1,2,3])
n1[-1:]

2    3
dtype: int64

In [105]:
import pandas as pd
n1=pd.Series([1,2,3])
n1=n1+2
n1

0    3
1    4
2    5
dtype: int64

In [112]:
import pandas as pd
n1=pd.DataFrame({'student':['sam','julia'],'marks':[70,80]})
n1

student  marks
0     sam     70
1   julia     80

In [115]:
import pandas as pd
iris=pd.read_csv('Iris.csv')
iris.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [116]:
import pandas as pd
iris=pd.read_csv('Iris.csv')
iris.tail()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica

In [119]:
import pandas as pd
iris=pd.read_csv('Iris.csv')
iris.shape

(150, 6)

In [120]:
import pandas as pd
iris=pd.read_csv('Iris.csv')
iris.iloc[0:4,5:7]

Species
0  Iris-setosa
1  Iris-setosa
2  Iris-setosa
3  Iris-setosa

In [124]:
import pandas as pd
iris=pd.read_csv('Iris.csv')
iris.drop([0,1,2],axis=0)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
5      6            5.4           3.9            1.7           0.4   
6      7            4.6           3.4            1.4           0.3   
7      8            5.0           3.4            1.5           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
3       Iris-setosa  
4       Iris-setosa  
5       Iris-setosa  
6       Iris-setosa  
7       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[147 rows x 6 columns]

In [132]:
import pandas as pd
iris=pd.read_csv('Iris.csv')
iris.mean

<bound method DataFrame.mean of       Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-seto

In [133]:
iris.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [136]:
def double_make():
    return s*2

In [141]:
iris[['SepalLengthCm','SepalWidthCm']].apply(double_make)

TypeError: double_make() takes 0 positional arguments but 1 was given

In [143]:
iris['Species'].value_counts()

Species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [150]:
iris.sort_values(by='PetalLengthCm')

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
22    23            4.6           3.6            1.0           0.2   
13    14            4.3           3.0            1.1           0.1   
14    15            5.8           4.0            1.2           0.2   
35    36            5.0           3.2            1.2           0.2   
36    37            5.5           3.5            1.3           0.2   
..   ...            ...           ...            ...           ...   
131  132            7.9           3.8            6.4           2.0   
105  106            7.6           3.0            6.6           2.1   
117  118            7.7           3.8            6.7           2.2   
122  123            7.7           2.8            6.7           2.0   
118  119            7.7           2.6            6.9           2.3   

            Species  
22      Iris-setosa  
13      Iris-setosa  
14      Iris-setosa  
35      Iris-setosa  
36      Iris-setosa  
..              ...  
131  Iris-virginica  
105  Iris-virginica  
117  Iris-virginica  
122  Iris-virginica  
118  Iris-virginica  

[150 rows x 6 columns]

In [146]:
iris.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [149]:
import pandas as pd
iris=pd.read_csv('Iris.csv')
iris.sort_values(by='PetalLengthCm')

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
22    23            4.6           3.6            1.0           0.2   
13    14            4.3           3.0            1.1           0.1   
14    15            5.8           4.0            1.2           0.2   
35    36            5.0           3.2            1.2           0.2   
36    37            5.5           3.5            1.3           0.2   
..   ...            ...           ...            ...           ...   
131  132            7.9           3.8            6.4           2.0   
105  106            7.6           3.0            6.6           2.1   
117  118            7.7           3.8            6.7           2.2   
122  123            7.7           2.8            6.7           2.0   
118  119            7.7           2.6            6.9           2.3   

            Species  
22      Iris-setosa  
13      Iris-setosa  
14      Iris-setosa  
35      Iris-setosa  
36      Iris-setosa  
..              ...  
131  Iris-virginica  
105  Iris-virginica  
117  Iris-virginica  
122  Iris-virginica  
118  Iris-virginica  

[150 rows x 6 columns]